package com.gl.ceir.panel.dto;

import java.io.Serializable;

import lombok.Data;

@Data
public class DeviceRequest implements Serializable {
	private static final long serialVersionUID = -946914686613090080L;
	private Integer pageNo;
	private Integer pageSize;
	private String source = "menu";
	private Integer featureId = 55;
	private Integer userId =  1367;
	private Integer userTypeId = 25;
	private String userType = "Device Repository";
	private String publicIp = "122.161.65.14";
	private String browser = "Chrome/Win10";
	
	private Integer soundLoudspeaker;
	private Integer sound35mmJack;
	private Integer softsimSupport;
	private Integer simSlot;
	private Integer selfieCameraType;
	private Integer ram;
	private String remark;
	private Integer removableEUICC;
	private Integer removableUICC;
	private Integer nonremovableEUICC;
	private Integer nonremovableUICC;
	private Integer networkTechnologyLTE;
	private Integer networkTechnologyGSM;
	private Integer networkTechnologyEVDO;
	private Integer networkTechnologyCDMA;
	private Integer networkTechnology7G;
	private Integer networkTechnology6G;
	private Integer networkTechnology5G;
	private Integer memoryInternal;
	private Integer memoryCardSlot;
	private Integer mainCameraType;
	private Double launchPriceAsianMarket;
	private Double launchPriceCambodiaMarket;
	private Double launchPriceEuropeMarket;
	private Double launchPriceInternationalMarket;
	private Double launchPriceUSMarket;
	private Double sourceOfCambodiaMarketPrice;
	private Double customPriceOfDevice;
	private Integer esimSupport;
	private Integer deviceState;
	private Integer commsRadio;
	private Integer commsNFC;
	private Integer batteryCapacity;
	private Integer id;
	private Integer imeiQuantity;
	private String deviceId;
	private String os;
	private Integer mdrStatus;
	private String startDate;
	private String endDate;
	private String columnName;
	private String sort;
	private String searchString;
	private String brandName;
	private String modelName;
	private Object deviceStatus;
	private String createdOn;
	private String modifiedOn;
	private String orderColumnName;
	private String order;
	private String allocationDate;
	private String announceDate;
	private String bandDetail;
	private String batteryCharging;
	private String batteryType;
	private String bodyDimension;
	private String bodyWeight;
	private String colors;
	private String commsBluetooth;
	private String commsGPS;
	private String commsNFCInterp;
	private String commsRadioInterp;
	private String commsUSB;
	private String commsWLAN;
	private String deviceType;
	private String discontinueDate;
	private String displayProtection;
	private String displayResolution;
	private String displaySize;
	private String displayType;
	private String esimSupportInterp;
	private String launchDate;
	private String mainCameraFeature;
	private String mainCameraSpec;
	private String mainCameraTypeInterp;
	private String mainCameraVideo;
	private String manufacturer;
	private String manufacturingLocation;
	private String marketingName;
	private String memoryCardSlotInterp;
	private String network2GBand;
	private String network3GBand;
	private String network4GBand;
	private String network5GBand;
	private String network6GBand;
	private String network7GBand;
	private String networkSpeed;
	private String networkTechnology5GInterp;
	private String networkTechnology6GInterp;
	private String networkTechnology7GInterp;
	private String networkTechnologyCDMAInterp;
	private String networkTechnologyEVDOInterp;
	private String networkTechnologyGSMInterp;
	private String networkTechnologyLTEInterp;
	private String oem;
	private String organizationId;
	private String osBaseVersion;
	private String platformCPU;
	private String platformChipset;
	private String platformGPU;
	private String reportedGlobalIssue;
	private String reportedLocalIssue;
	private String selfieCameraFeature;
	private String selfieCameraSpec;
	private String selfieCameraTypeInterp;
	private String selfieCameraVideo;
	private String sensor;
	private String simType;
	private String softsimSupportInterp;
	private String sound35mmJackInterp;
	private String soundLoudspeakerInterp;
	
	private String stateInterp;
	private String userDisplayName;
	
	private PageDto page;
}
   